name: Mirroring
on:
  push:
    branches:
      - '**'

  # Runs on wiki updates
  gollum:

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-EIP-600-REN-6-1-eip-5.git

jobs:
  mirroring:
    if: github.repository == 'Transf-ORM/Transf-ORM-CLI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{env.MIRROR_URL}}
          ssh_private_key: ${{secrets.MIRROR_SSH_KEY}}

  synchronize-wiki:
    name: Synchronize Wiki
    if: github.repository == 'Transf-ORM/Transf-ORM-CLI' && github.event_name == 'gollum'
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.MIRROR_SSH_KEY }}

    - name: Checkout wiki repository
      run: |
        git clone --mirror "git@github.com:${{ github.repository }}.wiki.git" wiki

    - name: Synchronize wiki to mirror
      run: |
        cd wiki;
        git push --mirror "git@github.com:EpitechPGE3-2025/G-EIP-600-REN-6-1-eip-5.wiki.git";